### ISSUE TITLE
how to use with sprintf() function.

### ISSUE THREAD

**Issue by msh2050** [AndrewMascolo/CountUpDownTimer#18]
it is noted in the examples : 

> // This DOES NOT format the time to 0:0x when seconds is less than 10.

> // if you need to format the time to standard format, use the sprintf() function.

please any example or hint

**Comment by AndrewMascolo** [comment]
void setup() {
Serial.begin(9600);

char buffer = "H:xx M:xx S:xx"; // something that will hold the modified string.  **char buffer[15];** works too.

int hours = 12;
int minutes = 35;
int seconds = 40;
sprintf(buffer, "H:%02d M:%02d S:%02d", hours, minutes, seconds); // %02d means you want a space of 2 filled with 0. "d" means the variable you are passing it will be a number.

Serial.println(buffer); // this should print out _H:12 M:35 S:40_
}

**Comment by msh2050** [comment]
thanks alot 👍
