### ISSUE TITLE
Missing "=" on header file in timer bool

### ISSUE THREAD

**Issue by dragoblaztr** [AndrewMascolo/CountUpDownTimer#23]
I'm looking at code and I found this mistake or if I'am wrong please let me know

		if ((_intTime = _InternalClock() ) - time > duration ) // check the time difference and see if 1 second has elapsed
		{

**Comment by AndrewMascolo** [comment]
It’s not a mistake, I’m assigning the value of _InternalClock to _intTime, then subtracting time from that result.

- Andrew
