### ISSUE TITLE
Subtract instantly after start

### ISSUE THREAD

**Issue by dragoblaztr** [AndrewMascolo/CountUpDownTimer#24]
is there a fix to improve the functionality of StartTimer() because I notice when it's called instantly is subtracted 1 s to the established time.

thanks in advanced

**Comment by AndrewMascolo** [comment]
No, that is how it’s supposed to be.

- Andrew

**Comment by dragoblaztr** [comment]
so, if do I want that way?

**Comment by AndrewMascolo** [comment]
When you count down from 60, you start at 59 and go down to 0. 

59-0 = 60 seconds

- Andrew
